# Generated by Django 2.2 on 2021-03-17 07:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('import_app', '0008_auto_20210303_1211'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0010_celeryscheduletask_on_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('cron', models.CharField(blank=True, max_length=250, null=True)),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meeting',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Perticular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('completion_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perticular_for_meeting', to='minutes_of_meeting.Meeting')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_for_perticular', to=settings.AUTH_USER_MODEL)),
                ('reminders', models.ManyToManyField(blank=True, related_name='reminder_for_tasks', to='reporting.CeleryScheduleTask')),
            ],
            options={
                'verbose_name': 'Perticular',
                'verbose_name_plural': 'Perticular',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('is_organizer', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_for_attendence', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_for_attendence', to='minutes_of_meeting.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_for_thread', to='import_app.Company')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_for_meeting_thread', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MeetingThread',
                'verbose_name_plural': 'MeetingThreads',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_thread_for_meeting', to='minutes_of_meeting.MeetingThread'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='reminder',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_for_meeting', to='reporting.CeleryScheduleTask'),
        ),
    ]
