# Generated by Django 2.2 on 2021-03-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_celeryscheduletask_on_datetime'),
        ('minutes_of_meeting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetinguser',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='perticular',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='perticular',
            name='reminders',
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendee',
            field=models.ManyToManyField(blank=True, related_name='attendee_for_meeting', to='minutes_of_meeting.MeetingUser'),
        ),
        migrations.AddField(
            model_name='perticular',
            name='cron',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='perticular',
            name='reminder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_for_task', to='reporting.CeleryScheduleTask'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='reminder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_for_meeting', to='reporting.CeleryScheduleTask'),
        ),
        migrations.CreateModel(
            name='MeetingPerticular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='minutes_of_meeting.Meeting')),
                ('perticular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perticulars', to='minutes_of_meeting.Perticular')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='perticular',
            field=models.ManyToManyField(through='minutes_of_meeting.MeetingPerticular', to='minutes_of_meeting.Perticular'),
        ),
    ]
