# Generated by Django 2.2 on 2021-05-06 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minutes_of_meeting', '0002_auto_20210317_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRecurringMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='cron',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='start_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='m_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RecurringMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('cron', models.CharField(blank=True, max_length=250, null=True)),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('meetings', models.ManyToManyField(through='minutes_of_meeting.MeetingRecurringMeeting', to='minutes_of_meeting.Meeting')),
            ],
            options={
                'verbose_name': 'RecurringMeeting',
                'verbose_name_plural': 'RecurringMeeting',
            },
        ),
        migrations.AddField(
            model_name='meetingrecurringmeeting',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_for_recurring_meetings', to='minutes_of_meeting.Meeting'),
        ),
        migrations.AddField(
            model_name='meetingrecurringmeeting',
            name='recurring_meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_meeting', to='minutes_of_meeting.RecurringMeeting'),
        ),
    ]
