# Generated by Django 2.2 on 2021-01-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210119_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='designation',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Designation'),
        ),
    ]
