# Generated by Django 2.2 on 2021-02-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_siteuser_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('PARTNER', 'partner')], default='ADMIN', max_length=20),
        ),
    ]
