# Generated by Django 2.2 on 2021-03-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210226_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.siteuser',),
        ),
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.siteuser',),
        ),
        migrations.CreateModel(
            name='PartnerUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.siteuser',),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='user_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee user'), ('PARTNER', 'Partner user'), ('ADMIN', 'Admin user')], default='EMPLOYEE', max_length=20),
        ),
    ]
