# Generated by Django 2.2 on 2021-03-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210317_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee user'), ('partner', 'Partner user'), ('admmin', 'Admin user')], default='employee', max_length=20),
        ),
    ]
