# Generated by Django 2.2 on 2021-04-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_siteuser_under'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='designation',
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee user'), ('manager', 'Manager user'), ('partner', 'Partner user'), ('admmin', 'Admin user')], default='employee', max_length=20),
        ),
    ]
