# Generated by Django 2.2 on 2021-06-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210408_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='using_software',
            field=models.BooleanField(default=False),
        ),
    ]
