# Generated by Django 2.2 on 2021-02-17 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBalanceMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='primary', max_length=20)),
                ('trial_bal_mapping', models.ManyToManyField(blank=True, to='import_app.TrialBalanceMapping')),
                ('trial_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_app.TrialBalance')),
            ],
        ),
    ]
