# Generated by Django 2.2 on 2021-02-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0002_trialbalancemapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialbalancemapping',
            name='trial_bal_mapping',
        ),
        migrations.RemoveField(
            model_name='trialbalancemapping',
            name='type',
        ),
        migrations.AddField(
            model_name='trialbalancemapping',
            name='groups',
            field=models.ManyToManyField(blank=True, to='import_app.Group'),
        ),
        migrations.AddField(
            model_name='trialbalancemapping',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_app.ParentGroup'),
        ),
    ]
