# Generated by Django 2.2 on 2021-02-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0003_auto_20210222_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialbalance',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='trial_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_app.TrialBalance'),
        ),
        migrations.AddField(
            model_name='ledgers',
            name='trial_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_app.TrialBalance'),
        ),
    ]
