# Generated by Django 2.2 on 2021-02-24 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('import_app', '0005_trialbalance_balance_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_app.Company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('person', 'company')},
            },
        ),
        migrations.AddField(
            model_name='company',
            name='persons',
            field=models.ManyToManyField(through='import_app.CompanyPerson', to=settings.AUTH_USER_MODEL),
        ),
    ]
