# Generated by Django 2.2 on 2021-02-24 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0005_trialbalance_balance_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalancemapping',
            name='custom_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_group_for_tbm', to='import_app.Group'),
        ),
        migrations.AddField(
            model_name='trialbalancemapping',
            name='custom_parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_parent_group_for_tbm', to='import_app.ParentGroup'),
        ),
        migrations.AlterField(
            model_name='trialbalancemapping',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='group_for_tbm', to='import_app.Group'),
        ),
        migrations.AlterField(
            model_name='trialbalancemapping',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_group_for_tbm', to='import_app.ParentGroup'),
        ),
    ]
