# Generated by Django 2.2 on 2021-02-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0006_auto_20210224_1253'),
        ('import_app', '0006_auto_20210224_1335'),
    ]

    operations = [
    ]
