# Generated by Django 2.2 on 2021-03-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0007_merge_20210226_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentgroup',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
