# Generated by Django 2.2 on 2021-03-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0008_auto_20210303_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.CharField(blank=True, default='vikas.pandey9323@gmail.com', max_length=150, null=True),
        ),
    ]
