# Generated by Django 2.2 on 2021-03-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0009_auto_20210321_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companygroup',
            name='groups',
        ),
        migrations.AddField(
            model_name='companygroup',
            name='groupname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='companygroup',
            name='company_id',
        ),
        migrations.AddField(
            model_name='companygroup',
            name='company_id',
            field=models.ManyToManyField(to='import_app.Company'),
        ),
    ]
