# Generated by Django 2.2 on 2021-03-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0010_auto_20210322_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='custom',
        ),
    ]
