# Generated by Django 2.2 on 2021-03-28 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0011_remove_group_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTR2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_no', models.CharField(blank=True, max_length=90, null=True)),
                ('customer_billing_name', models.CharField(blank=True, max_length=90, null=True)),
                ('report1', models.BooleanField(default=False)),
                ('report2', models.BooleanField(default=False)),
                ('report3', models.BooleanField(default=False)),
                ('report4', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='GSTR2_invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('total_value', models.FloatField(blank=True, null=True)),
                ('inv_typ', models.CharField(blank=True, max_length=3, null=True)),
                ('gstr2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_app.GSTR2')),
            ],
            options={
                'unique_together': {('invoice_no', 'invoice_date', 'total_value', 'inv_typ')},
            },
        ),
        migrations.CreateModel(
            name='GSTPurchaseValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_billing_name', models.CharField(blank=True, max_length=90, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=90, null=True)),
                ('inv_no', models.CharField(blank=True, max_length=20, null=True)),
                ('inv_date', models.DateField(blank=True, null=True)),
                ('total_value', models.FloatField(blank=True, null=True)),
                ('inv_typ', models.CharField(blank=True, max_length=3, null=True)),
                ('txval', models.FloatField(blank=True, null=True)),
                ('camt', models.FloatField(blank=True, null=True)),
                ('samt', models.FloatField(blank=True, null=True)),
                ('iamt', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('report5', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='GSTR2_gst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txval', models.FloatField(blank=True, null=True)),
                ('camt', models.FloatField(blank=True, null=True)),
                ('samt', models.FloatField(blank=True, null=True)),
                ('iamt', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('gstr2_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_app.GSTR2_invoice')),
            ],
            options={
                'unique_together': {('gstr2_invoice', 'txval', 'camt', 'samt', 'iamt', 'rate')},
            },
        ),
    ]
