# Generated by Django 2.2 on 2021-03-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0012_gstpurchasevalues_gstr2_gstr2_gst_gstr2_invoice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voucheritem',
            unique_together={('ledger_name_temp', 'amt', 'type', 'voucher_id')},
        ),
    ]
