# Generated by Django 2.2 on 2021-04-01 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0013_auto_20210329_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgers',
            name='under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_app.Group'),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='close_bal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='open_bal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
