# Generated by Django 2.2 on 2021-04-06 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0012_merge_20210406_1311'),
        ('import_app', '0014_auto_20210401_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgers',
            name='under_custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.CustomGroup'),
        ),
        migrations.AlterField(
            model_name='ledgers',
            name='under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.Group'),
        ),
    ]
