# Generated by Django 2.2 on 2021-04-08 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0015_auto_20210406_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialbalance',
            name='close_bal',
        ),
        migrations.RemoveField(
            model_name='trialbalance',
            name='open_bal',
        ),
        migrations.CreateModel(
            name='ProfitLoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_name', models.CharField(max_length=80)),
                ('total_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=20)),
                ('auto_timedate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_app.Company')),
            ],
            options={
                'unique_together': {('company_id', 'head_name', 'total_amt', 'type')},
            },
        ),
        migrations.CreateModel(
            name='PLItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_app.ProfitLoss')),
            ],
            options={
                'unique_together': {('pl', 'name', 'amt')},
            },
        ),
    ]
