# Generated by Django 2.2 on 2021-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0016_auto_20210409_0027'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='vouchers',
        #     name='bank_date',
        #     field=models.CharField(blank=True, max_length=15, null=True),
        # ),
        # migrations.AddField(
        #     model_name='vouchers',
        #     name='instrument_date',
        #     field=models.CharField(blank=True, max_length=15, null=True),
        # ),
        # migrations.AddField(
        #     model_name='vouchers',
        #     name='instrument_number',
        #     field=models.CharField(blank=True, max_length=30, null=True),
        # ),
        # migrations.AddField(
        #     model_name='vouchers',
        #     name='is_reconciled',
        #     field=models.BooleanField(default=False),
        # ),
    ]
