# Generated by Django 2.2 on 2021-04-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0017_auto_20210411_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='is_reconciled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
