# Generated by Django 2.2 on 2021-05-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0017_auto_20210419_1505'),
        ('import_app', '0017_auto_20210424_1051'),
    ]

    operations = [
    ]
