# Generated by Django 2.2 on 2021-05-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0018_merge_20210506_1138'),
        ('import_app', '0018_auto_20210411_1511'),
    ]

    operations = [
    ]
