# Generated by Django 2.2 on 2021-05-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0019_merge_20210529_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
