# Generated by Django 2.2 on 2021-06-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0020_auto_20210529_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_version', models.CharField(max_length=10)),
                ('blocked_versions', models.CharField(max_length=110)),
                ('latest_software_path', models.CharField(max_length=50)),
                ('download_link', models.URLField(max_length=90)),
                ('total_downloads_till_date', models.IntegerField(default=0)),
                ('total_downloads_current_version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
