# Generated by Django 2.2 on 2021-06-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0021_appversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=90)),
                ('user_mobile', models.CharField(max_length=90)),
                ('user_password', models.CharField(max_length=90)),
                ('user_id', models.CharField(max_length=90)),
                ('tally_path', models.CharField(max_length=150)),
                ('schedule_time_mins', models.CharField(max_length=5)),
                ('schedule_time_hrs', models.CharField(max_length=5)),
                ('port_number', models.CharField(max_length=4)),
            ],
        ),
    ]
