# Generated by Django 2.2 on 2021-06-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0022_configurationbackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationbackup',
            name='user_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='configurationbackup',
            name='user_mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='configurationbackup',
            name='user_password',
            field=models.CharField(max_length=30),
        ),
    ]
