# Generated by Django 2.2 on 2021-06-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0023_auto_20210616_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='blocked_versions',
            field=models.CharField(max_length=150),
        ),
    ]
