# Generated by Django 2.2 on 2021-03-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misreportscheduleemail',
            name='mis_name',
            field=models.CharField(blank=True, choices=[('financial_dashboard', 'Financial Dashboard'), ('liquidity_barometer', 'Liquidity Barometer'), ('profit_loss', 'Profit & Loss Account'), ('fund_flow', 'Fund Flow Statement'), ('provisional_cash_flow', 'Provisional Cashflow'), ('debtors_ageing', 'Debtors Ageing Report'), ('creditors_ageing', 'Creditors Ageing Report'), ('crucial_numbers', 'Crucial Numbers')], max_length=40, null=True),
        ),
    ]
