# Generated by Django 2.2 on 2021-03-15 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0008_auto_20210303_1211'),
        ('reporting', '0002_auto_20210313_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misreportscheduleemail',
            name='title',
        ),
        migrations.CreateModel(
            name='TallyPortalDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgst', models.FloatField(blank=True, null=True)),
                ('igst', models.FloatField(blank=True, null=True)),
                ('cess', models.FloatField(blank=True, null=True)),
                ('gst_r1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_app.GSTR1_gst')),
                ('gst_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_app.GSTSalesValues')),
            ],
        ),
    ]
