# Generated by Django 2.2 on 2021-03-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20210315_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tallyportaldifference',
            old_name='cess',
            new_name='cgst',
        ),
        migrations.AddField(
            model_name='tallyportaldifference',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tallyportaldifference',
            name='txval',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
