# Generated by Django 2.2 on 2021-03-16 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0008_auto_20210303_1211'),
        ('reporting', '0004_auto_20210316_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyportaldifference',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='import_app.Company'),
            preserve_default=False,
        ),
    ]
