# Generated by Django 2.2 on 2021-03-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_celeryscheduletask'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeryscheduletask',
            name='instance_id',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='celeryscheduletask',
            name='task_name',
            field=models.CharField(blank=True, choices=[('mis_schedule_mail_task', 'mis_schedule_mail_task'), ('task_meeting_thread', 'task_meeting_thread'), ('notify_meeting_create', 'notify_meeting_create'), ('notify_meeting_close', 'notify_meeting_close'), ('meeting_reminder', 'meeting_reminder'), ('task_reminder', 'task_reminder')], max_length=40, null=True),
        ),
    ]
