# Generated by Django 2.2 on 2021-03-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0008_auto_20210303_1211'),
        ('reporting', '0005_auto_20210316_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misreportscheduleemail',
            old_name='croninput',
            new_name='cron',
        ),
        migrations.RemoveField(
            model_name='celeryscheduletask',
            name='title',
        ),
        migrations.AlterUniqueTogether(
            name='misreportscheduleemail',
            unique_together={('company_id', 'mis_name', 'days')},
        ),
    ]
