# Generated by Django 2.2 on 2021-03-16 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0014_remove_clockedschedule_enabled'),
        ('reporting', '0006_auto_20210316_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misreportscheduleemail',
            name='task',
        ),
        migrations.AddField(
            model_name='misreportscheduleemail',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_for_mis_report', to='django_celery_beat.PeriodicTask'),
        ),
    ]
