# Generated by Django 2.2 on 2021-03-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_auto_20210316_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeryscheduletask',
            name='class_name',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
