# Generated by Django 2.2 on 2021-03-16 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_auto_20210316_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeryscheduletask',
            name='on_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
