# Generated by Django 2.2 on 2021-03-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_tallyportaldifference_company'),
        ('reporting', '0010_celeryscheduletask_on_datetime'),
    ]

    operations = [
    ]
