# Generated by Django 2.2 on 2021-03-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_celeryscheduletask_on_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celeryscheduletask',
            name='task_name',
            field=models.CharField(blank=True, choices=[('mis_schedule_mail_task', 'mis_schedule_mail_task'), ('task_meeting_thread', 'task_meeting_thread'), ('notify_meeting_create', 'notify_meeting_create'), ('notify_meeting_close', 'notify_meeting_close'), ('meeting_reminder', 'meeting_reminder'), ('task_reminder', 'task_reminder'), ('crucial_numbers_mail', 'crucial_numbers_mail')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='misreportscheduleemail',
            name='cron',
            field=models.CharField(blank=True, default='0 0 17 * SAT', max_length=70),
        ),
    ]
