# Generated by Django 2.2 on 2021-03-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_auto_20210320_2027'),
        ('reporting', '0005_tallyportaldifference_company'),
    ]

    operations = [
    ]
