# Generated by Django 2.2 on 2021-03-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_auto_20210321_0239'),
        ('reporting', '0012_merge_20210320_2114'),
        ('reporting', '0012_auto_20210321_0532'),
    ]

    operations = [
    ]
