# Generated by Django 2.2 on 2021-04-01 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0011_remove_group_custom'),
        ('tally', '0005_auto_20210325_0148'),
        ('reporting', '0013_merge_20210324_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='TrialBalanceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Note')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Report')),
            ],
        ),
        migrations.CreateModel(
            name='NoteCustomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.CustomGroup')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Note')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='custom_groups',
            field=models.ManyToManyField(through='reporting.NoteCustomGroup', to='tally.CustomGroup'),
        ),
    ]
