# Generated by Django 2.2 on 2021-04-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0014_auto_20210401_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrialBalanceReport',
            new_name='ReportNote',
        ),
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.ManyToManyField(through='reporting.ReportNote', to='reporting.Note'),
        ),
    ]
