# Generated by Django 2.2 on 2021-04-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0015_auto_20210401_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misreportscheduleemail',
            name='cron',
            field=models.CharField(blank=True, default='0 17 * * *', max_length=70),
        ),
    ]
