# Generated by Django 2.2 on 2021-05-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0019_merge_20210506_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celeryscheduletask',
            name='task_name',
            field=models.CharField(blank=True, choices=[('mis_schedule_mail_task', 'mis_schedule_mail_task'), ('task_meeting_thread', 'task_meeting_thread'), ('notify_meeting_create', 'notify_meeting_create'), ('notify_meeting_close', 'notify_meeting_close'), ('meeting_reminder', 'meeting_reminder'), ('task_reminder', 'task_reminder'), ('crucial_numbers_mail', 'crucial_numbers_mail'), ('ledgers_data_html_email', 'ledgers_data_html_email')], max_length=40, null=True),
        ),
    ]
