# Generated by Django 2.2 on 2021-03-21 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='primary', max_length=90)),
                ('balance_sheet_type', models.CharField(blank=True, choices=[('Assets', 'Assets'), ('Liabilities', 'Liabilities')], max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.Company')),
                ('under', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.CustomGroup')),
            ],
            options={
                'unique_together': {('name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='primary', max_length=90)),
                ('balance_sheet_type', models.CharField(blank=True, choices=[('Assets', 'Assets'), ('Liabilities', 'Liabilities')], max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.Company')),
                ('under', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.Group')),
            ],
            options={
                'unique_together': {('name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('name', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('creation_date', models.CharField(blank=True, max_length=10, null=True)),
                ('alteration_date', models.CharField(blank=True, max_length=10, null=True)),
                ('altered_by', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=90, null=True)),
                ('email', models.CharField(blank=True, max_length=95, null=True)),
                ('is_cost_center_on', models.BooleanField(default=False)),
                ('mailing_name', models.CharField(blank=True, max_length=20, null=True)),
                ('gst', models.CharField(blank=True, max_length=15, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('auto_timedate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.Company')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.Group')),
            ],
        ),
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_timedate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('custom_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.CustomGroup')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.Ledger')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.Company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_for_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('person', 'company')},
            },
        ),
        migrations.AddField(
            model_name='company',
            name='persons',
            field=models.ManyToManyField(related_name='persons_for_company', through='tally.CompanyPerson', to=settings.AUTH_USER_MODEL),
        ),
    ]
