# Generated by Django 2.2 on 2021-03-21 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.CustomGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='ledger',
            unique_together={('name', 'company', 'group')},
        ),
    ]
