# Generated by Django 2.2 on 2021-03-21 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0003_auto_20210321_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=90, null=True)),
                ('creation_date', models.CharField(blank=True, max_length=10, null=True)),
                ('alteration_date', models.CharField(blank=True, max_length=10, null=True)),
                ('altered_by', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=90, null=True)),
                ('email', models.CharField(blank=True, max_length=95, null=True)),
                ('is_cost_center_on', models.BooleanField(default=False)),
                ('mailing_name', models.CharField(blank=True, max_length=20, null=True)),
                ('gst', models.CharField(blank=True, max_length=15, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('auto_timedate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.Company')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.CustomGroup')),
            ],
            options={
                'unique_together': {('name', 'company', 'group')},
            },
        ),
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_timedate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('custom_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.CustomGroup')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally.Ledger')),
            ],
        ),
    ]
