# Generated by Django 2.2 on 2021-04-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0007_auto_20210401_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='group_type',
            field=models.CharField(blank=True, choices=[('Assets', 'Assets'), ('Liabilities', 'Liabilities')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(blank=True, choices=[('Assets', 'Assets'), ('Liabilities', 'Liabilities')], max_length=20, null=True),
        ),
    ]
