# Generated by Django 2.2 on 2021-04-01 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0008_auto_20210401_1633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyperson',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='companyperson',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyperson',
            name='person',
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_app.Company'),
        ),
        migrations.AlterField(
            model_name='group',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_group', to='import_app.Company'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_app.Company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyPerson',
        ),
    ]
