# Generated by Django 2.2 on 2021-04-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0009_auto_20210401_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='group_type',
            field=models.CharField(blank=True, choices=[('BS', 'Balance Sheet'), ('P&L', 'Profit & Loss')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(blank=True, choices=[('BS', 'Balance Sheet'), ('P&L', 'Profit & Loss')], max_length=20, null=True),
        ),
    ]
