# Generated by Django 2.2 on 2021-04-03 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0014_auto_20210401_0620'),
        ('tally', '0010_auto_20210401_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tb_for_company', to='import_app.Company'),
        ),
    ]
