# Generated by Django 2.2 on 2021-04-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0011_auto_20210402_1759'),
        ('tally', '0011_trialbalance_company'),
    ]

    operations = [
    ]
