# Generated by Django 2.2 on 2021-04-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0012_merge_20210406_1311'),
        ('tally', '0012_merge_20210406_1714'),
    ]

    operations = [
    ]
