# Generated by Django 2.2 on 2021-04-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0012_merge_20210406_1714'),
        ('tally', '0012_merge_20210405_2128'),
    ]

    operations = [
    ]
