# Generated by Django 2.2 on 2021-04-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0012_merge_20210406_1311'),
        ('tally', '0013_merge_20210407_1320'),
    ]

    operations = [
    ]
