# Generated by Django 2.2 on 2021-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0014_auto_20210408_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customgroup',
            old_name='closing_balance',
            new_name='closing_balance_cr',
        ),
        migrations.RenameField(
            model_name='customgroup',
            old_name='opening_balance',
            new_name='opening_balance_cr',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='closing_balance',
            new_name='closing_balance_cr',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='opening_balance',
            new_name='opening_balance_cr',
        ),
        migrations.AddField(
            model_name='customgroup',
            name='closing_balance_dr',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='opening_balance_dr',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='closing_balance_dr',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='opening_balance_dr',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True),
        ),
    ]
