# Generated by Django 2.2 on 2021-04-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0013_merge_20210408_1923'),
        ('tally', '0014_merge_20210409_1345'),
        ('tally', '0015_auto_20210408_1755'),
    ]

    operations = [
    ]
