# Generated by Django 2.2 on 2021-04-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0015_auto_20210408_1755'),
        ('tally', '0013_merge_20210408_1923'),
    ]

    operations = [
    ]
