# Generated by Django 2.2 on 2021-04-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0016_merge_20210409_1414'),
        ('tally', '0016_merge_20210409_1431'),
    ]

    operations = [
    ]
